foodies/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar import urls as debug_toolbar

if not settings.TESTING:
    urlpatterns = [
        path("", include("customers.urls")),
        path("admin/", admin.site.urls),
        path("products/", include("products.urls")),
        path("customers/", include("customers.urls")),
        path("employees/", include("employees.urls")),
        path("orders/", include("orders.urls")),
        path("__debug__/", include(debug_toolbar)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns = [
        path("", include("orders.urls")),
        path("admin/", admin.site.urls),
        path("products/", include("products.urls")),
        path("customers/", include("customers.urls")),
        path("employees/", include("employees.urls")),
        path("orders/", include("orders.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import OrderListView, OrderCreateView, OrderCreateAPIView, OrderDetailView

urlpatterns = [
    path("", OrderListView.as_view(), name="orders"),
    path("add-order/", OrderCreateView.as_view(), name="create_order"),
    path("api/add-order/", OrderCreateAPIView.as_view(), name="create_order_api"),
    path("order-details/<int:id>/", OrderDetailView.as_view(), name="detail_order"),
]

employees/models.py
from django.contrib.auth.models import User
from django.db import models

from companies.models import Company


class Employee(models.Model):
    user: models.OneToOneField = models.OneToOneField(User, on_delete=models.CASCADE)
    company: models.ForeignKey = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"

    def __str__(self) -> str:
        return self.user.username

templates/navigation/nav.html
<aside
  class="border-t border-t-gray-200 sm:h-full sm:border-r sm:border-r-gray-200 text-orange-500 font-bold">
  <nav class="sm:h-full sm:flex sm:flex-col sm:justify-between sm:items-center">
    <ul class="flex items-center justify-evenly sm:flex-col">
      <li
        class="group relative sm:w-full flex items-center justify-center py-7 px-3 border-t-2 border-transparent sm:border-t-0 hover:text-orange-600 hover:border-t-orange-600 cursor-pointer transition-colors ease-linear">
        <a class="relative flex items-center gap-2 sm:inline-block sm:w-6 sm:h-6"
          href="{% url 'customers' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30"
            height="30" color="currentColor" fill="none"
            class="absolute left-1/2 -translate-x-1/2 group-hover:-translate-y-3/4 sm:group-hover:translate-y-0 transition-transform">
            <path
              d="M7.5 19.5C7.5 18.5344 7.82853 17.5576 8.63092 17.0204C9.59321 16.3761 10.7524 16 12 16C13.2476 16 14.4068 16.3761 15.3691 17.0204C16.1715 17.5576 16.5 18.5344 16.5 19.5"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <circle cx="12" cy="11" r="2.5" stroke="currentColor"
              stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <path
              d="M17.5 11C18.6101 11 19.6415 11.3769 20.4974 12.0224C21.2229 12.5696 21.5 13.4951 21.5 14.4038V14.5"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <circle cx="17.5" cy="6.5" r="2" stroke="currentColor"
              stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <path
              d="M6.5 11C5.38987 11 4.35846 11.3769 3.50256 12.0224C2.77706 12.5696 2.5 13.4951 2.5 14.4038V14.5"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <circle cx="6.5" cy="6.5" r="2" stroke="currentColor"
              stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
          </svg>
          <span
            class="invisible rounded sm:absolute sm:z-20 group-hover:visible group-hover:translate-y-2/3 sm:group-hover:translate-y-0 sm:group-hover:translate-x-[50px] sm:group-hover:bg-white sm:group-hover:px-3 sm:py-1 sm:group-hover:shadow-md transition-all ease-linear quicksand-700">
            Clientes
          </span>
        </a>
      </li>
      <li
        class="group relative sm:w-full flex items-center justify-center py-7 px-3 border-t-2 border-transparent sm:border-t-0 hover:text-orange-600 hover:border-t-orange-600 cursor-pointer transition-colors ease-linear">
        <a class="relative flex items-center gap-2 sm:inline-block sm:w-6 sm:h-6"
          href="{% url 'orders' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30" height="30" color="currentColor" fill="none" class="absolute left-1/2 -translate-x-1/2 group-hover:-translate-y-3/4 sm:group-hover:translate-y-0 transition-transform">>
            <path d="M2 16C2 12.8182 4.23858 11 7 11C9.76142 11 12 12.8182 12 16H2Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />
            <path d="M5 8H9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
            <path d="M10 16C10 17.6569 8.65685 19 7 19C5.34315 19 4 17.6569 4 16" stroke="currentColor" stroke-width="1.5" />
            <circle cx="20" cy="17" r="2" stroke="currentColor" stroke-width="1.5" />
            <path d="M16 8C17.3333 8.63768 20 11.1739 20 15M15.9899 5H16.5366C17.5214 5 18.4246 5.57927 18.8809 6.5034C19.1964 7.14264 18.8809 8 17.9849 8H15.9899M15.9899 5V8M15.9899 5H12.9444M15.9899 8C15.9899 9.91304 15.7776 16 12 16H17.6665" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
          <span
            class="invisible rounded sm:absolute sm:z-20 group-hover:visible group-hover:translate-y-2/3 sm:group-hover:translate-y-0 sm:group-hover:translate-x-[50px] sm:group-hover:bg-white sm:group-hover:px-3 sm:py-1 sm:group-hover:shadow-md transition-all ease-linear quicksand-700">
            Pedidos
          </span>
        </a>
      </li>
      <li
        class="group relative sm:w-full flex items-center justify-center py-7 px-3 border-t-2 border-transparent sm:border-t-0 hover:text-orange-600 hover:border-t-orange-600 cursor-pointer transition-colors ease-linear">
        <a class="relative flex items-center gap-2 sm:inline-block sm:w-6 sm:h-6"
          href="{% url "products" %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30"
            height="30" color="currentColor" fill="none"
            class="absolute left-1/2 -translate-x-1/2 group-hover:-translate-y-3/4 sm:group-hover:translate-y-0 transition-transform">
            <path
              d="M12 7V4.34832C12 2.1606 12.3737 1.6318 14.4968 2.22769L18 3.21095"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
            <path
              d="M6 7L7.1398 18.1606C7.31099 19.8368 7.39658 20.6749 7.96796 21.1813C9.1458 22.225 14.7472 22.3198 16.032 21.1813C16.6034 20.6749 16.689 19.8368 16.8602 18.1606L18 7"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
            <path d="M5 7H19" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" />
            <path d="M7 12H17" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" />
            <path d="M7 16H17" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" />
          </svg>
          <span
            class="invisible rounded sm:absolute sm:z-20 group-hover:visible group-hover:translate-y-2/3 sm:group-hover:translate-y-0 sm:group-hover:translate-x-[50px] sm:group-hover:bg-white sm:group-hover:px-3 sm:py-1 sm:group-hover:shadow-md transition-all ease-linear quicksand-700">
            Productos
          </span>
        </a>
      </li>
    </ul>
    <div class="flex items-center justify-evenly sm:flex-col">
      {% if perms.employees.view_employee or user.is_superuser %}
      <div class="group relative sm:w-full flex items-center justify-center py-7 px-3 border-t-2 border-transparent sm:border-t-0 hover:text-orange-600 hover:border-t-orange-600 cursor-pointer transition-colors ease-linear">
        <a class="relative flex items-center gap-2 sm:inline-block sm:w-6 sm:h-6"
          href="{% url 'employees' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30"
            height="30" color="currentColor" fill="none"
            class="absolute left-1/2 -translate-x-1/2 group-hover:-translate-y-3/4 sm:group-hover:translate-y-0 transition-transform">
            <path d="M14 8.99988H18" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" />
            <path d="M14 12.4999H17" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" />
            <rect x="2" y="2.99988" width="20" height="18" rx="5"
              stroke="currentColor" stroke-width="1.5"
              stroke-linejoin="round" />
            <path d="M5 15.9999C6.20831 13.4188 10.7122 13.249 12 15.9999"
              stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
              stroke-linejoin="round" />
            <path
              d="M10.5 8.99988C10.5 10.1044 9.60457 10.9999 8.5 10.9999C7.39543 10.9999 6.5 10.1044 6.5 8.99988C6.5 7.89531 7.39543 6.99988 8.5 6.99988C9.60457 6.99988 10.5 7.89531 10.5 8.99988Z"
              stroke="currentColor" stroke-width="1.5" />
          </svg>
          <span
            class="invisible rounded sm:absolute sm:z-20 group-hover:visible group-hover:translate-y-2/3 sm:group-hover:translate-y-0 sm:group-hover:translate-x-[50px] sm:group-hover:bg-white sm:group-hover:px-3 sm:py-1 sm:group-hover:shadow-md transition-all ease-linear quicksand-700">
            Empleados
          </span>
        </a>
      </div>
      {% endif %}
      <div class="group relative sm:w-full flex items-center justify-center py-7 px-3 border-t-2 border-transparent sm:border-t-0 hover:text-orange-600 hover:border-t-orange-600 cursor-pointer transition-colors ease-linear">
        <form action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="relative flex items-center gap-2 sm:inline-block sm:w-6 sm:h-6">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30"
              height="30" color="currentColor" fill="none"
              class="absolute left-1/2 -translate-x-1/2 group-hover:-translate-y-3/4 sm:group-hover:translate-y-0 transition-transform">
              <path
                d="M11 3L10.3374 3.23384C7.75867 4.144 6.46928 4.59908 5.73464 5.63742C5 6.67576 5 8.0431 5 10.7778V13.2222C5 15.9569 5 17.3242 5.73464 18.3626C6.46928 19.4009 7.75867 19.856 10.3374 20.7662L11 21"
                stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
              <path
                d="M21 12L11 12M21 12C21 11.2998 19.0057 9.99153 18.5 9.5M21 12C21 12.7002 19.0057 14.0085 18.5 14.5"
                stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                stroke-linejoin="round" />
            </svg>
            <span
              class="invisible rounded sm:text-nowrap sm:absolute sm:z-20 group-hover:visible group-hover:translate-y-2/3 sm:group-hover:translate-y-0 sm:group-hover:translate-x-[50px] sm:group-hover:bg-white sm:group-hover:px-3 sm:py-1 sm:group-hover:shadow-md transition-all ease-linear quicksand-700">
              Cerrar sesión
            </span>
          </button>
        </form>
      </div>
    </div>
  </nav>
</aside>